[project]
name = "stac-geoparquet-hashing"
version = "0.1.0"
description = "Hash and sort into stac-geoparquet"
readme = "README.md"
authors = [
    { name = "Pete Gadomski", email = "pete.gadomski@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.0",
    "pandas>=3.0.5",
    "pyarrow>=25.0.0",
    "rich>=15.0.0",
    "rustac>=0.9.16",
    "stac-hash>=0.0.2",
    "typer>=0.27.1",
]

[project.scripts]
sgph = "sgph:app"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pandas-stubs>=3.0.5.260730",
    "pytest>=8.0",
    "ruff>=0.16.3",
]
