[project]
name = "sgph"
version = "0.1.0"
description = "Hash and sort into stac-geoparquet"
readme = "README.md"
authors = [
    { name = "Pete Gadomski", email = "pete.gadomski@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "pandas>=3.0.5",
    "pyarrow>=25.0.0",
    "rustac>=0.9.16",
    "stac-hash>=0.0.1",
    "typer>=0.27.1",
]

[project.scripts]
sgph = "sgph:app"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pandas-stubs>=3.0.5.260730",
]
